example_env  # unused function (tests/conftest.py:22)
example_env  # unused variable (tests/test_easy_config.py:47)
example_env  # unused variable (tests/test_easy_config.py:57)
example_config_env  # unused function (tests/conftest.py:35)
example_config_env  # unused variable (tests/test_easy_config.py:51)
